codecov:
  bot: jayvdb
  max_report_age: 48
  strict_yaml_branch: master

coverage:
  precision: 1
  round: up
  range: 75..95
  status:
    project:
      default:
        enabled: yes
    patch:
      default:
        enabled: yes
    changes:
      default:
        enabled: yes

  ignore:
    - pywikibot/daemonize.py
    - pywikibot/families/__init__.py
    - pywikibot/scripts/preload_sites.py
    - pywikibot/scripts/version.py
    - scripts/dataextend.py
    - scripts/maintenance/colors.py
    - scripts/maintenance/make_i18n_dict.py
    - scripts/maintenance/wikimedia_sites.py
    - scripts/userscripts/
    - tests/pwb/

  notify:
    irc:
      default:
        server: libera.chat
        channel: pywikibot
