version = 1

test_patterns = ["tests/**"]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["dev-requirements.txt"]

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 80
  type_checker = "mypy"
